### ISSUE TITLE
[TODO] Support for v5

### ISSUE THREAD

**Issue by nerdguyahmad** [nerdguyahmad/randomstuff.py#23]
## Overview
Support for v5 should be added.

## TODO List
- [x] Authorization (only for v5) using the `Authorization` header instead of `X-api-key`
- [x] [`/covid`](https://docs.pgamerx.com/endpoints/covid) endpoint support
- [x] [Customisation](https://docs.pgamerx.com/endpoints/ai#customisation) support on `/ai`
- [ ] [`/facts`](https://docs.pgamerx.com/premium/facts) endpoint support
- [x] [Flags blacklisting](https://docs.pgamerx.com/endpoints/joke#available-flags-for-blacklisting-are) support for `/jokes` endpoint.
- [x] Async Client

**Comment by nerdguyahmad** [comment]
v2.0 released on PyPi :rocket:
